# Generated by Django 4.2.2 on 2023-07-12 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=200)),
                ("method", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("request_data", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
