# Generated by Django 4.2.2 on 2023-07-07 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"verbose_name": "Choice", "verbose_name_plural": "Choices"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Question", "verbose_name_plural": "Questions"},
        ),
    ]
