# Generated by Django 4.2.2 on 2023-07-10 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_city_product_supplier_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
